# 站点配置@start
site:
  ## Favicon
  favicon: /img/favicon.ico
  ## 头像
  avatar: /img/avatar.png
# 站点配置@end

# 导航配置@start
nav:
  ## 站点聚合
  group:
    项目:
      FlecUI: https://github.com/talen8/hexo-theme-flecui || /img/favicon.ico
    演示:
      FlecUI_Demo: https://flecui-demo.talen.top/ || /img/favicon.ico
      FlecBLOG: https://talen.top || /img/favicon.ico
    # 类别:
    #   名称: 链接 || 图标
  ## 页面LOGO
  logo: 
    class: text # 显示类型  i_class | text | img
    custom: FlecBLOG # 显示内容  flec-logo | FlecBLOG | /img/logo.png
  ## 中心菜单
  menu:
    首页: /
    文库:
      文章列表: /archives/ || flec-folder-fill
      全部分类: /categories/ || flec-checkbox-fill
      全部标签: /tags || flec-price-tag-fill
    友联:
      友情链接: /links/ || flec-group-fill
      宝藏博主: javascript:travelling() || flec-gift-fill
    我的:
      关于本站: /about/ || flec-contacts-fill
    # 菜单:
    #   菜单项: 路径 || 图标
  ## 功能按钮
  button:
    random: false # 随机文章跳转
    console: false # 控制台
    # 自定义按钮（左至右）
    custom:
    # - name: 开往 - 友链接力 # 显示文字
    #   url: https://www.travellings.cn/go.html # 跳转链接
    #   icon: flec-train-line # 图标
    #   onclick: # 点击事件
    #   id: travellings_button # id
# 导航配置@end

# 首页顶部@start
hometop:
  enable: true # 是否开启
  ## 技能陈列
  banner:
    title: 前景可待<br>未来可期 # 左上大文字（可用html标签）
    text: Hexo Theme FlecUI # 左上小文字
    ## 左下跳转按钮
    group:
      热门: /tags/热门/ || flec-fire-fill || linear-gradient(to right,#f65,#ffbf37)
      教程: /tags/教程/ || flec-book-mark-fill || linear-gradient(to right,#358bff,#15c6ff)
      精选: /tags/精选/ || flec-star-smile-fill || linear-gradient(to right,#18e7ae,#1eebeb)
      # 名称: /路径/ || 图标 || 颜色
    ## 右侧轮播图标（76x76）
    icon:
      # 名称:
      #   img: 图片
      #   color: 背景色
      HTML:
        img: https://txycos.talen.top/skill/HTML.png
        color: '#e9572b'
      CSS:
        img: https://txycos.talen.top/skill/CSS.png
        color: '#264de4'
      JavaScript:
        img: https://txycos.talen.top/skill/JavaScript.png
        color: '#f7cb4f'
      Git:
        img: https://txycos.talen.top/skill/Git.png
        color: '#df5b40'
      Docker:
        img: https://txycos.talen.top/skill/Docker.png
        color: '#57b6e6'
      Vue:
        img: https://txycos.talen.top/skill/Vue.png
        color: '#ffffff'
      Python:
        img: https://txycos.talen.top/skill/Python.png
        color: '#ffffff'
      Linux:
        img: https://txycos.talen.top/skill/Linux.png
        color: '#ffffff'
      Photoshop:
        img: https://txycos.talen.top/skill/Photoshop.png
        color: '#31a8ff'
      PremierePro:
        img: https://txycos.talen.top/skill/PremierePro.png
        color: '#9999ff'
      AfterEffects:
        img: https://txycos.talen.top/skill/AfterEffects.png
        color: '#9999ff'
      Illustrator:
        img: https://txycos.talen.top/skill/Illustrator.png
        color: '#ff9a00'
      LightroomClassic:
        img: https://txycos.talen.top/skill/LightroomClassic.png
        color: '#31a8ff'
  ## 置顶列表（文章的置顶需要在文章front matter中添加“recommend: true”）
  recommendList:
    sup: 置顶 # 左下小文字
    title: FlecUI 主题文档 # 左下大文字
    url: https://flecui.talen.top/ # 点击跳转链接
    img: /img/default.png # 背景图片
    color: "none" # 阴影颜色
# 首页顶部@end

# 侧边栏@start
aside:
  # 参考值：about（个人信息）、newestPost（最新文章）、allInfo（网站信息）、flip（公众号二维码）、calendar（日历日程）、ads（谷歌广告）
  # 说明：noSticky为侧边栏固定的信息（滑动不跟随），Sticky为侧边栏不固定的信息（滑动跟随）
  ## 主页显示的侧边栏内容
  home:
    noSticky: "about"
    Sticky: "allInfo"
  ## 文章页显示的侧边栏内容
  post:
    noSticky: "about"
    Sticky: "newestPost"
  ## 页面页中显示的侧边栏内容
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  ## 侧边栏位置
  position: right # left：左侧 | right：右侧
  ## 个人信息卡片
  card:
    style: 0 # 样式选择  0：默认样式 | 1：HEO同款样式
    ## 头像设置
    author:
      img: /img/avatar.png # 头像图片
      sticker: /img/happy-sticker.png # 表情图片（26x26）
    url: /about/ # 头像跳转链接
    background: # 背景图片，不填不显示
    ## 顶部按钮打招呼语句
    sayhello:
      morning: 一日之计在于晨
      noon: 吃饱了才有力气干活
      afternoon: 集中精力，攻克难关
      night: 不要太劳累了，早睡更健康
      goodnight: 睡个好觉，保证精力充沛
    ## 顶部按钮点击切换语句
    sayhello2:
     - 目之所及，皆是回忆
     - 心之所想，皆是过往
     - 眼之所看，皆是遗憾
    content: 永远相信美好的事情即将发生。 # 介绍文本，支持HTML标签，仅style为1时生效
    ## 社交图标，不要超过4个
    information:
      # 名称：链接 || 图标
      Email: mailto:talen2004@163.com || flec-mail-line
      Github: https://github.com/talen8 || flec-github-line
    ## 关注按钮，仅style为0时生效
    button:
      enable: true # 是否开启
      text: 订阅本站 # 按钮文本
      url: /subscribe/ # 跳转链接
  ## 二维码卡片
  flip:
    favicon: # 右下角头像
    face: # 正面图片
    backface: # 翻转图片
    backcolor: "var(--flec-blue)" # 背景颜色
  ## 目录卡片
  toc:
    post: true # 在文章页显示
    page: false # 在页面页显示
    vague: true # 模糊效果
  ## 网站信息卡片-标签
  tags:
    enable: false # 是否显示标签
    limit: 20 # 显示标签最大数，高于此值显示全部标签按钮
    ## 高亮显示标签
    highlight_list:
     - Hexo
     - Hexo

      - Hexo

  ## 网站信息卡片-归档
  archive:
    enable: false # 是否显示归档
    type: "month" # 显示类型  month按月 | year按年
  ## 网站信息卡片-建站信息
  siteinfo:
    postcount: true # 文章数
    wordcount: true # 总字数
    pv: true # 访问量PV
    uv: true # 访客数UV
    updatetime: true # 最后更新日期
    runtimeenable: true # 建站时间
    runtime: "2024-01-01 00:00:00" # 格式：yyyy-MM-dd hh-mm-ss
# 侧边栏@end

# 首页文章配置@start
index_post_list:
  direction: column # 文章方向  row：列表 | column：卡片
  cover: both # 文章封面  left：左侧 | right在：右侧 | both：两侧交替
  content: false # 文章摘要  1：手动填写 | 2：自动获取 | 3：截取内容 | false：不显示
  length: 500  # 摘要截取长度
# 首页文章配置@end

# 页面配置@start
page:
  error: true # 是否开启404页面
  tags: true # 是否开启标签页
  categories: true # 是否开启分类页
  ## 默认设置
  default:
    ## 默认图片
    cover:
      - /img/default.png
# 页面配置@end

# 文章配置@start
post:
  ## 默认设置
  default:
    ## 文章默认图片
    cover:
      - /img/default.png
    locate: 济宁 # 文章发布默认地址
    ## 文章默认版权
    copyright:
      enable: true # 是否开启
      ## 作者信息设置
      author:
        img: # 显示头像，不填写默认显示avatar
        url: /about/ # 头像跳转地址
      license: CC BY-NC-SA 4.0 # 许可协议
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh # 许可协议链接
  ## 顶部文章信息
  meta:
    date: false # 发布日期
    updated: false # 更新日期
    locate: false # 位置
    wordcount: false # 字数
    readtime: false # 访问uv
    pv: false # 浏览量pv
    comment: false # 评论数
  ## 打赏
  award:
    enable: false # 是否开启打赏
    title: 感谢您的赞赏。 # 赞赏标题
    desc: 因为有你们的支持，我才体会到写文章的价值。 # 赞赏名单小文字
    appreciators: /about # 赞赏名单跳转
    ## 赞赏方式
    list:
      # - name: 方式名称
      #   qcode: 二维码图片链接
      #   url: 点击跳转链接
      #   color: 颜色
      - name: 微信
        qcode: https://txycos.talen.top/web/rewardWechatQR.png
        url: https://txycos.talen.top/web/rewardWechatQR.png
        color: var(--flec-purple)
      - name: 支付宝
        qcode: https://txycos.talen.top/web/rewardAlipayQR.png
        url: https://txycos.talen.top/web/rewardAlipayQR.png
        color: var(--flec-black)
      # - name: 爱发电
      #   qcode: https://txycos.talen.top/web/rewardAfdianQR.png
      #   url: https://txycos.talen.top/web/rewardAfdianQR.png
      #   color: var(--flec-black)
  ## 分享按钮
  share:
    enable: false # 是否开启分享按钮
    ## 分享按钮列表
    list:
    #  - qq
    #  - weibo
    #  - twitter
    #  - facebook
    #  - telegram
    #  - whatsapp
    #  - linkedin
  rss: /atom.xml # 订阅按钮跳转链接
  ## 文章主题色获取
  covercolor:
    enable: false
    mode: local # 取色方式  local：本地取色 | api：img2color取色
    api: https://api.qjqq.cn/api/Imgcolor?img= # api地址
    time: 43200000 # 取色间隔（毫秒），默认为12小时
# 文章配置@end

# 页脚配置@start
footer:
  ## 上方图标
  information:
    ## 头像
    author: 
      enable: false
      image: /img/avatar.png
    left: # 左侧图标
      # 名称：链接 || 图标
      # Github: https://github.com/talen8 || flec-github-line
    right: # 右侧图标
      # Bilibili: https://space.bilibili.com/479887195 || flec-bilibili-line
  ## 导航栏
  group:
    # 导航:
    #   归档: /archives/
    #   分类: /categories/
    #   标签: /tags/
    # 服务:
    #   腾讯云: https://cloud.tencent.com/
    #   51la统计: https://v6.51.la/
    # 支持:
    #   打赏记录: /about/
    # 协议:
    #   Cookies: /cookies/
    #   用户协议: /privacy/
    #   版权协议: /copyright/
  ## 随机友链，开启前需先配置links
  randomlink: false
  ## 隐私助手弹窗跳转
  privacy: # /privacy/
  ## 版权(Copyright)跳转
  license: # /license/
  ## 右侧链接，可以放备案号
  links:
    - name: 主题
      url: https://github.com/talen8/hexo-theme-flecui
    # - name: 名称
    #   url: 跳转链接
# 页脚配置@end

# 主题配色@start
theme_color:
  dark: "#DEB247" # 暗色模式
  dark_op: "#DEB24723" # 暗色模式透明
  dark_op_deep: "#DEB247DD" # 暗色模式透明深色
  dark_none: "#DEB24700" # 暗色模式透明无色
  light: "#8042EF" # 亮色模式
  light_op: "#8042EF23" # 亮色模式透明
  light_op_deep: "#8042EFDD" # 亮色模式透明深色
  light_none: "#8042EF01" # 亮色模式透明无色
# 主题配色@end

# 主题显示模式@start
display_mode:
  type: auto # 模式选择  auto 自动切换 | dark 暗色模式 | light 亮色模式
  universe: true # 星空背景，仅深色模式下生效
# 主题显示模式@end

# 文底推荐文章@start
related_post:
  enable: false
  limit: 2 # 推荐文章数量
  date_type: created # 推荐依据  created 创建日期 | updated 更新日期
# 文底推荐文章@end

# 加载动画@start
loading:
  ## 全局加载动画
  fullpage:
    enable: true
    image: /img/avatar.png
  ## 顶部加载胶囊
  pace: true
# 加载动画@end

# 中控台扩展@start
console_plus: false
# 中控台扩展@end

# 右键菜单@start
right_menu:
  enable: false # 是否开启
  commentBarrage: false # 是否显示热评开关
  ## 简繁切换
  translate:
    enable: false
    defaultEncoding: 2 # 默认语言  1：默认繁体 | 2：默认简体
    translateDelay: 0 # 首次加载翻译迟疑时间
  ## 自定义菜单项列表
  custom_list:
    # - name: 随机短文
    #   click: toRandomPost()
    #   id: menu-randomPost
    #   class:
    #   icon: flec-dice-line
    # - name: 全部分类
    #   click: pjax.loadUrl('/categories/')
    #   id:
    #   class:
    #   icon: flec-checkbox-fill
    # - name: 全部标签
    #   click: pjax.loadUrl('/tags/')
    #   id:
    #   class:
    #   icon: flec-price-tag-fill
    # - name: 赞助主题
    #   click: window.open('https://afdian.net/a/talen/', '_blank') # 外链用 window.open，pjax 无法请求跨域内容
    #   id:
    #   class:
    #   icon: flec-afdian-line
# 右键菜单@end

# 复制@start
copy:
  enable: false # 是否开启
  ## 增加版权信息
  copyright:
    enable: false
    limit: 50 # 字数超过时生效
# 复制@end

# 代码块@start
highlight:
  enable: true
  limit: 200 # 代码行高限制
  copy: true # 是否开启复制按钮
  expand: true # 是否默认展开
  theme: default # 代码块样式  default 默认 | mac 苹果终端
  color: default # 代码配色  default | dark | funky | okaidia | tomorrow | twilight | darcula | solarized-dark | solarized-light | material | github
# 代码块@end

# 图片灯箱（Fancybox）@start
# 介绍：https://fancyapps.com/fancybox/
lightbox: false
# 图片灯箱（Fancybox）@end

# Mermaid标签@start
# 介绍：https://mermaid.js.org/
mermaid: false
# Mermaid标签@end

# 快捷菜单@start
keyboard:
  enable: false
  ## 键盘控制配置
  list:
    # - name: 按键名称
    #   key: 按键
    #   func: 方法
    #   flec: flec内置方法(flec.'function')
    #   url: 跳转链接
    - name: 关闭快捷键功能
      key: K
      func: keyboard
    - name: 打开中控台
      key: A
      flec: showConsole
    - name: 播放/暂停音乐
      key: M
      flec: musicToggle
    - name: 打开友情链接
      key: L
      url: "/links/"
# 快捷菜单@end

# 懒加载@start
lazyload:
  enable: false
  field: site # 作用页面  post 仅文章页面使用 | site 全站页面使用
  placeholder: /img/loading.gif # 加载中显示图片
  errorimg: /img/error_load.webp # 加载失败显示图片
# 懒加载@end

# 字体@start
font:
  font-size: 16px # 字体大小
  code-font-size: 16px # 代码字体大小
  font-family: 'PingFang SC,Hiragino Sans GB,Microsoft YaHei' # 字体
  code-font-family: 'monospace, monospace' # 代码字体
# 字体@end

# LaTeX公式@start
katex:
  enable: false
  per_page: false # 是否在每页都加载
  copytex: false # 是否开启复制公式
# LaTeX公式@end

# 音乐胶囊@start
capsule:
  enable: false
  id: 1994908354 # 歌单id
  server: netease # 播放列表的服务商  netease：网易云 | tencent：腾讯 | ytmusic：YouTube Music | spotify：Spotify
  type: playlist # 播放列表的类型  song：单曲 | playlist：歌单 | album：专辑 | artist：歌手
# 音乐胶囊@end

# 访问统计@start
busuanzi: false # 是否开启统计
busuanzi_use: 0 # 统计来源  0：原版 | 1：青秸(other: 其它自定义的busuanzi平台)
# 访问统计@end

# 字数统计@start
# 开启前需安装字数统计插件
wordcount: false
# 字数统计@end

# 网页黑白@start
memorial:
  enable: false
  # 日期, (M-D)
  date:
    - "7-8" #七八卢沟桥事变
    - "9-18" #九一八事变/建军节
    - "12-13" #南京国家公祭日
# 网页黑白@end

# Open Graph@start
# 介绍：https://ogp.me/
# 使用：https://developers.facebook.com/docs/sharing/webmasters/
OpenGraph:
  enable: false
  ## 分享设置选项
  options:
  #  twitter_card:
  #  twitter_image:
  #  twitter_id:
  #  twitter_site:
  #  google_plus:
  #  fb_admins:
  #  fb_app_id:
# Open Graph@end

# 评论@start
comment:
  use: # 选择评论系统  waline, twikoo, valine, artalk
  commentBarrage: false # 热评开关
  lazyload: false # 懒加载
  count: false # 评论数展示
  pv: false # 是否使用评论系统统计页面访问量
  avatar: https://cravatar.cn # 评论用户头像
  ## 最新评论
  newest_comment:
    enable: true
    storage: .5 # 缓存时间，单位为天
# 评论@end

# twikoo 配置信息
twikoo: # https://twikoo.js.org/
  envId: # url: https://twikoo.sondy.top/
  region: # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
  style: true # 开启后使用自定义样式
  accessToken: # AccessToken
  option: # twikoo option

# waline 配置信息
waline: # https://waline.js.org/
  envId:  # url: https://waline.wzsco.top
  pageview: false # 是否开启页面访问量统计
  option: # waline配置项

# valine 配置信息
valine:
  appId: # leancloud application app id
  appKey: # leancloud application app key
  serverURLs: # 此配置适用于国内自定义域名用户，海外版本将自动检测
  avatar: # https://valine.js.org/avatar.html
  visitor: false
  style: true # 开启后使用自定义样式
  option: # options list

# artalk 配置信息
artalk:
  server: # 后端地址
  site: # 站点名
  option: # options

# 搜索@start
search:
  ## 开启前需安装搜索插件
  enable: false
  type: local # 搜索方式  algolia：Algolia搜索 | local：本地搜索
  ## 推荐标签
  tags:
    - FlecUI
    - Hexo
  ## Algolia搜索配置
  algolia:
    ## 每页显示的搜索条数
    hits:
      per_page: 6
  ## 本地搜索配置
  local:
    ## 是否启用预加载
    preload: false
    CDN:
# 搜索@end

# Post Chat AI@start
# 后台地址：https://ai.tianli0.top/
tianli_talk:
  enable: false
  title: 智能客服与搜索 # 标题
  key:  # 购买的Key
  ## 自定义选项，参考https://ai.tianli0.top/codeMaker.html，不填则使用默认值
  option:
    # defaultInput: false
    # upLoadWeb: true
    # userTitle: Flec Chat
    # userDesc: 你好，我是 Flec 智能客服，有什么可以帮助你的？
    # showInviteLink: ''
    # blackDom:
    #   - .aplayer
# Post Chat AI@end

# 文章摘要AI@start
post_ai:
  enable: false
  modelName: FlecGPT # 右侧模型名称
  key: # Key
  talk: 我是AI摘要生成助理FlecGPT，FlecGPT在静态部署时进行摘要的撰写，并且在访客访问时通过转译后的文本摘要实现工具。我在这里只负责已经生成的摘要显示，你无法与我直接沟通，但我可以回答一些预设的问题。 # 自介
  randomPost: false # 随机文章按钮
  report:  # 举报链接，不填不显示
  tips: 此内容根据文章生成，并经过人工审核，仅用于文章内容的解释与总结 # 底部提示
# 文章摘要AI@end

# 站点验证@start
verify_site:
  # - name: baidu-site-verification
  #   content: xxxxxxxxxxxx
  # - name: msvalidate.01
  #   content: xxxxxxxxxxxx
  # - name: google-site-verification
  #   content: xxxxxxxxxxxx
# 站点验证@end

# CSS前缀@start
# 开启后可增强浏览器兼容性，但会增加20%的体积
css_prefix: false
# CSS前缀@end

# PWA@start
# 介绍：https://developer.mozilla.org/zh-CN/docs/Web/Progressive_web_apps
pwa:
  enable: false
  manifest: /manifest.json # manifest.json 文件路径
  theme_color: "#006a73" # 主题颜色
  mask_icon: /img/pwa/favicon.ico # 遮罩图标
  apple_touch_icon: /img/pwa/favicon.ico # 苹果触摸图标
  bookmark_icon: /img/pwa/favicon.ico # 书签图标
  favicon_32_32: /img/pwa/favicon_32.ico # 32x32图标
  favicon_16_16: /img/pwa/favicon_16.ico # 16x16图标
# PWA@end

# 谷歌广告@start
google_adsense:
  enable: false
  auto_ads: false # 自动广告
  enable_page_level_ads: true # 页面级广告
  aside_card: true # 侧边栏卡片广告，需在aside中添加ads
  post_card: true # 文章卡片广告（首页文章列表）
  post_content: true # 文章内容广告（文章内容底部广告）
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js # 谷歌广告js
  client: ca-pub-XXXXXXXXXXXXXX # client id
  slot: 123456789 # slot id，需在关闭自动广告时填写
# 谷歌广告@end

# 404页面@start
errorpage:
  img: /img/404.png # 图片
  text: 糟糕 页面走丢了 # 文字
  recommendList: true # 推荐文章列表
# 404页面@end

# 订阅页面@start
subscribe:
  ## 是否开启，开启前需完成相关配置
  enable: false
  follow: https://api.follow.it/subscription-form/xxxxx=/8
# 订阅页面@end

# 即刻短文@start
says:
  ## 是否开启，开启前需完成相关配置
  enable: false
  strip: 30 # 展示条数
  home_mini: false # 主页轮播条
  style: 0 # 样式  0:默认样式
# 即刻短文@end

# 相册@start
# photo相册页，开启前需完成相关配置
photo: 
  enable: false
  ## Bar分类栏
  bar: 
    enable: false
    tips: 年份类别
    # Bar分类栏的内容
    list:
      # - tag || 显示文字
      - 相册 || 全部
      - 2024 || 2024
  # Bar分类栏最右侧更多按钮
  more:
    enable: false
    # 跳转链接 || 显示文字
    link: /album/ || 影集
  # 相册加载loading图标
  loading: /img/loading.gif

# album影集页，开启前需完成相关配置
album: 
  enable: false
  # Bar分类栏
  bar: 
    enable: false
    tips: 影集类别
    # Bar分类栏的内容
    list:
      # - tag || 显示文字
      - 影集 || 全部
      - 日常 || 日常
  # Bar分类栏最右侧更多按钮
  more:
    enable: false
    # 跳转链接 || 显示文字
    link: /photos/ || 相册
  # 相册加载loading图标
  loading: /img/loading.gif
# 相册@end

# 最近评论@start
recent_comments:
  enable: false # 是否开启，开启前需完成相关配置
  limit: 50 # 评论数，waline最多支持50条
  cache: 0.2 # 缓存时间，单位为天
  console: false # 控制台按钮
  page: /recentcomments/ # 最近评论页面
# 最近评论@end

# 留言板@start
envelope:
  ## 是否开启，开启前需完成相关配置
  enable: false
  line: 10 # 显示行数
  speed: 20 # 播放速度
  hover: true # 鼠标悬停暂停
  loop: true # 循环播放
  page: /message/ # 留言板页面
# 留言板@end

# 音乐页面@start
# meeting-api，用于音乐胶囊和音乐馆页
meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r"
music:
  enable: false
  ## 音乐ID  歌单ID | 专辑ID | 歌手ID
  id: 1994908354
  ## 播放列表的服务商  netease：网易云 | tencent：腾讯 | ytmusic：YouTube Music | spotify：Spotify
  server: netease
  ## 播放列表的类型  song：单曲 | playlist：歌单 | album：专辑 | artist：歌手
  type: playlist
  ## 初始音量  0.8 = 80%，范围 0 到 1
  volume: 0.8
  ## 互斥模式，即同时只能有一个播放器播放
  mutex: true
# 音乐页面@end

# 插入代码@start
extends:
  ## 在head中插入
  head:
    # - <script src="https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js"></script>
  ## 在body中插入
  body:
# 插入代码@end

# CDN@start
CDN:
  ## 主题内js的cdn配置
  internal: local  # local/jsdelivr/unpkg/cdnjs/custom
  ## 第三方js的cdn配置
  third_party: cdnjs  # local/jsdelivr/unpkg/cdnjs/custom
  ## 在url中添加版本号
  version: true
  ## 自定义格式
  # 示例: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format: //open.lightxi.com/cdnjs/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
  ## 覆盖的CDN链接
  option:
    flecicon_css: https://txycos.talen.top/web/flecicon/iconfont.css
    # algolia_search:
    # instantsearch:
    # pjax:
    # twikoo:
    # waline_js:
    # waline_css:
    # katex:
    # katex_copytex:
    # lazyload:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # pace_js:
    # swiper_css:
    # swiper_js:
    # busuanzi_js:
    # snackbar_js:
# CDN@end
